[build]
  command = "CI=false GENERATE_SOURCEMAP=false DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  TSC_COMPILE_ON_ERROR = "true"